# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a52592b00531fd4e50684da0592d74f8640992e8fe50352e3913946b27c0ae4687645997386ac12901bd326f988bd7fda6be77d58973abda8b651a53b6775b

test:
  secret_key_base: 8231a74f19fce0eae811e783c80de94eae09c6710e6841e1c62dc44665f53a8e66c20faa07a2b1668513bd8ae9b4da35c982ee922accc71ddc2c2891aa01a8e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
